### ISSUE TITLE
Health Check Stuck in "starting" State Even Though Container Functions Normally

### ISSUE THREAD

**Issue by brianzhouzc** [edgd1er/nordvpn-proxy#45]
I'm encountering an issue where the container appears to be functioning as expected (proxy is up and working, connections are routed properly), but the container's health check remains stuck in the "starting" state indefinitely:

```bash
CONTAINER ID   IMAGE                               COMMAND                  CREATED         STATUS                            PORTS                                                                                                                                         NAMES
e6c4a89dee4f   edgd1er/nordvpn-proxy:latest        "runsvdir /etc/servi…"   7 minutes ago   Up 7 minutes (health: starting)   0.0.0.0:1080->1080/tcp, :::1080->1080/tcp, 0.0.0.0:8888->8888/tcp, :::8888->8888/tcp                                                          nordvpn-proxy
```

It seems to be something related to the health check. Let me know what other info/logs you need from me!

**Comment by edgd1er** [comment]
for healthcheck, start-period is 1m. if the container is still starting after 1 minute, the healtcheck cannot be performed.

Could you run /etc/service/openvpn/healthcheck.sh ?

**Comment by brianzhouzc** [comment]
I got `56`:
```bash
9400b171794c:/etc/service# /etc/service/openvpn/healthcheck.sh
9400b171794c:/etc/service# echo $?
56
```

The container is now showing as unhealthy, but it's been running for 7hrs now and the proxy seems to be working fine.

**Comment by edgd1er** [comment]
Could you run again the healtcheck with bash -x to view what test is failing ?

**Comment by brianzhouzc** [comment]
This is the result I got, sorry I'm not too familiar with bash and healthchecks:

```bash
9400b171794c:/etc/service# bash -x /etc/service/openvpn/healthcheck.sh
+ set -e -u -o pipefail
+ EXIT_WHEN_IP_NOTEXPECTED=0
+ WRITE_OVPN_STATUS=0
+ IP_FILE=/tmp/ip.txt
+ ARGS=
+ [[ -f /etc/service/utils.sh ]]
+ source /etc/service/utils.sh
++ DEBUG=0
++ [[ 0 =~ (true|1) ]]
++ SOCKET=unix-connect:/run/openvpn.sock
++ OVPN_STATUS_FILE=/var/tmp/ovpn_status
++++ dirname -- /etc/service/utils.sh
+++ cd -- /etc/service
+++ pwd
++ MAIN_DIR=/etc/service/..
+++ date '+%Y-%m-%d %H:%M:%S'
++ TIME_FORMAT='2025-02-06 07:05:25'
++ nordvpn_api=https://api.nordvpn.com
++ nordvpn_dl=downloads.nordcdn.com
++ nordvpn_cdn=https://downloads.nordcdn.com/configs/files
++ nordvpn_doc=https://haugene.github.io/docker-transmission-openvpn/provider-specific/#nordvpn
++ possible_protocol='tcp, udp'
++ NORDVPN_TESTS=
++ CONFIGDIR=/config
++ [[ ! -d /config ]]
++ export VPN_PROVIDER_HOME=/config
++ VPN_PROVIDER_HOME=/config
+ [[ ! '' =~ -v ]]
+ HOST=google.com
+ [[ -z google.com ]]
+ ping -c 2 -w 5 google.com
+ STATUS=0
+ [[ 0 -ne 0 ]]
+ check_dnssec
+ msg=
++ dig sigfail.verteiltesysteme.net @127.0.0.1 -p 53
++ grep -c SERVFAIL
+ dns_servfail_expected=1
++ dig +short sigok.verteiltesysteme.net @127.0.0.1 -p 53
+ dns_ip_expected='sigok.rsa2048-sha256.ippacket.stream.
195.201.14.36'
+ [[ 0 -eq 1 ]]
+ [[ -z sigok.rsa2048-sha256.ippacket.stream.
195.201.14.36 ]]
+ [[ -n '' ]]
+ true
+ check_openvpn
++ pgrep openvpn
++ wc -l
+ OPENVPN=1
+ [[ 1 -ne 1 ]]
++ find /config/ -type f -iname '*.ovpn' '!' -iname 'default*'
+ ovpnConf=/config/us8268.nordvpn.com.ovpn
++ basename /config/us8268.nordvpn.com.ovpn
++ sed s/.ovpn//
+ nordvpn_hostname=us8268.nordvpn.com
++ awk '/remote /{print $2}' /config/us8268.nordvpn.com.ovpn
+ expectedIp=212.102.47.95
+ [[ 212.102.47.95 =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\. ]]
+ net_expected=212.102.47.
++ curl -s https://myexternalip.com/raw
+ foundIp=45.143.82.68
+ [[ 45.143.82.68 =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\. ]]
+ net_found=45.143.82.
++ echo load-stats
++ socat -s - unix-connect:/run/openvpn.sock
++ tail -1
' LOAD='SUCCESS: nclients=0,bytesin=70070278058,bytesout=7470109849
++ echo state
++ socat -s - unix-connect:/run/openvpn.sock
++ sed -n 2p
+ STATE=$'1738798161,CONNECTED,SUCCESS,10.100.0.2,212.102.47.95,443,172.16.0.3,44328\r'
+ write_status_file $'1738798161,CONNECTED,SUCCESS,10.100.0.2,212.102.47.95,443,172.16.0.3,44328\r'
++ echo $'1738798161,CONNECTED,SUCCESS,10.100.0.2,212.102.47.95,443,172.16.0.3,44328\r'
++ grep -oE '(NOT|)CONNECTED'
+ STATUS=CONNECTED
+ [[ 0 -ne 0 ]]
 =~ CONNECTED ]]1,CONNECTED,SUCCESS,10.100.0.2,212.102.47.95,443,172.16.0.3,44328
+ changeTinyListenAddress
++ getTinyListen
++ grep -E 'Listen [0-9]+' /config/tinyproxy.conf
++ cut '-d ' -f2
+ listen_ip4=172.16.0.3
++ getEthIp
++ ip -j -4 a show eth0
++ jq -r '.[].addr_info[0].local'
+ current_ip4=172.16.0.3
+ [[ ! -z 172.16.0.3 ]]
+ [[ ! -z 172.16.0.3 ]]
+ [[ 172.16.0.3 != 172.16.0.3 ]]
+ checkproxies -s
+ [[ -s =~ -s ]]
+ FAILED=0
++ TCF=/run/secrets/TINY_CREDS
++ [[ -f /run/secrets/TINY_CREDS ]]
++ TCREDS=
++ curl -4 -sm 10 -x http://9400b171794c:8888 https://ifconfig.me/ip
+ IP=
```

**Comment by edgd1er** [comment]
http proxy does not return any ip.

Could you run checkhttp ?

and
source /etc/service/utils.sh
testhproxy
testsproxy
getTinyListen

**Comment by brianzhouzc** [comment]
Here are the outputs:

```bash
9400b171794c:/etc/service# checkhttp ?
?
9400b171794c:/etc/service#  source /etc/service/utils.sh
9400b171794c:/etc/service# testhproxy
IP is 45.143.82.68
9400b171794c:/etc/service# testsproxy
curl through socks proxy to https://ifconfig.me/ip failed
9400b171794c:/etc/service# getTinyListen
172.16.0.3
```

**Comment by edgd1er** [comment]
something is odd.
http proxy goes through sock's proxy to exit.
http proxy should not be able to exit if socks proxy is down.

there is maybe a glitch here. I'll look at it this evening.

**Comment by brianzhouzc** [comment]
Thanks, I should mention that I'm connecting to the container with SOCKS5, and everything seems to be working.

**Comment by edgd1er** [comment]
> Thanks, I should mention that I'm connecting to the container with SOCKS5, and everything seems to be working.

I pushed a new image with testhproxy fixed (and updated to alpine 3.21). the image was operating properly

**Comment by brianzhouzc** [comment]
> > Thanks, I should mention that I'm connecting to the container with SOCKS5, and everything seems to be working.
> 
> I pushed a new image with testhproxy fixed (and updated to alpine 3.21). the image was operating properly

Thanks! I updated my container to the latest image, and can confirm that both `testhproxy` and `testsproxy` returns a valid ip:
```bash
9400b171794c:/etc/service# source /etc/service/utils.sh
9400b171794c:/etc/service# testhproxy
IP is 185.228.19.11
9400b171794c:/etc/service# testsproxy
IP is 185.228.19.11
```
However, the status of the container is still showing as `starting`, and become `unhealthy` after a while:
```bash
CONTAINER ID   IMAGE                                                 COMMAND                  CREATED         STATUS                            PORTS                                                                                                                                         NAMES
5c83b1009ff8   edgd1er/nordvpn-proxy:latest                          "runsvdir /etc/servi…"   8 minutes ago   Up 8 minutes (health: starting)   0.0.0.0:1080->1080/tcp, :::1080->1080/tcp, 0.0.0.0:8888->8888/tcp, :::8888->8888/tcp 
```
```bash
CONTAINER ID   IMAGE                                                 COMMAND                  CREATED          STATUS                      PORTS                                                                                                                                         NAMES
5c83b1009ff8   edgd1er/nordvpn-proxy:latest                          "runsvdir /etc/servi…"   16 minutes ago   Up 16 minutes (unhealthy)   0.0.0.0:1080->1080/tcp, :::1080->1080/tcp, 0.0.0.0:8888->8888/tcp, :::8888->8888/tcp
```

Not sure if it's related, but if I run `checkhttp` and `checksocks` the output is empty:
```bash
9400b171794c:/etc/service# source /etc/service/utils.sh
9400b171794c:/etc/service# checkhttp

9400b171794c:/etc/service# checksocks

```

**Comment by brianzhouzc** [comment]
Yep, everything seems to be fine:
```bash
9400b171794c:/etc/service# curl -s 'https://nordvpn.com/wp-admin/admin-ajax.php?action=get_user_info_data' | jq .host.ip_address
"94.156.149.86"
9400b171794c:/etc/service# curl -s https://api.nordvpn.com/v1/helpers/ips/insights | jq .ip
"94.156.149.86"
9400b171794c:/etc/service# ip -j a | jq .[].ifname
"lo"
"tun0"
"eth0"
```

**Comment by edgd1er** [comment]
that's good news.
Now, to check what is failing, could you run 
set -x
healtcheck.sh


if it fails, then a message is sent to stderr ie container stderr.
ps: i'll be offline for a week.

**Comment by brianzhouzc** [comment]
Thanks for all the help - healthcheck.sh doesn't seem to return anything, and I'm not sure why. I might just have to leave it like this since it's working fine - just the status being `unhealthy`

```bash
9400b171794c:/etc/service/openvpn# set -x
+ set -x
9400b171794c:/etc/service/openvpn# ./healthcheck.sh 
+ ./healthcheck.sh
9400b171794c:/etc/service/openvpn#
```

**Comment by edgd1er** [comment]
according to you last comment healthcheck seems empty.

could try a bash -x ./healthcheck.sh ?
